*** Settings ***
Resource    ../../../../variables/Variables.robot    
Resource    ../../../../keyword/Keyword.robot
	
*** Test Cases ***
################### [Create] Employee Management ###################
M32_1_0_2_000_EmployeeManagement_Create_VerifyScreen [Verify screen page "Create Employee Management"]
    [Documentation]    Step is :    
	...   1. open link : https://login.smartcondo.net/en  
	...   2. login
	...   3. click ข้อมูลมาสเตอร์
	...   4. click menu จัดการพนักงาน
	...   5. click add button

    [Setup]    Open Browser To Login Page Super Admin



	#========== Click Setting Menu BankAccountManagement ======
	Click Setting Menu    ${MENU_LBL_HOMETOP_ADMIN_EMPLOYEEMANAGEMENT_LOCATOR}    ${MENU_LBL_HOMETOP_ADMIN_EMPLOYEEMANAGEMENT_TH}    ${MENU_LBL_SETTING_EMPLOYEEMANAGEMENT_LOCATOR}    ${MENU_LBL_SETTING_EMPLOYEEMANAGEMENT_TH}   ${EMPLOYEEMANAGEMENTINFORMATION_SEARCH_LBL_EMPLOYEEMANAGEMENTINFORMATION_HEADER_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_SEARCH_LBL_EMPLOYEEMANAGEMENTINFORMATION_HEADER_TH}    ${EMPLOYEEMANAGEMENTINFORMATION_SEARCH_LBL_EMPLOYEEMANAGEMENTINFORMATION_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_SEARCH_LBL_EMPLOYEEMANAGEMENTINFORMATION_TH}
	
	
	#========== Check BankAccountManagement ======
	#Click Add Bank account
	Click Element Page    ${EMPLOYEEMANAGEMENTINFORMATION_BTN_ADD_LOCATOR}
	Sleep    0.5s



	#Varify Screen : Add employee Header
	Wait Until Contains Element Text Should Be    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_HEADER_ADDEMPLOYEE_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_HEADER_ADDEMPLOYEE_TH}

	#Varify Screen : Employee Type
	Wait Until Contains Element Text Should Be    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_EMPLOYEETYPE_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_EMPLOYEETYPE_TH}

	#Varify Screen : Title
	Wait Until Contains Element Text Should Be    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_TITLE_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_TITLE_TH}

	#Varify Screen : First name
	Wait Until Contains Element Text Should Be    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_FIRSTNAME_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_FIRSTNAME_TH}

	#Varify Screen : Last name
	Wait Until Contains Element Text Should Be    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_LASTNAME_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_LASTNAME_TH}

	#Varify Screen : Phone number
	Wait Until Contains Element Text Should Be    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_PHONENUMBER_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_PHONENUMBER_TH}

	#Varify Screen : Active For Projects
	Wait Until Contains Element Text Should Be    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_ACTIVEFORPROJECTS_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_ACTIVEFORPROJECTS_TH}

	#Varify Screen : Select / Unselect all
	Wait Until Contains Element Text Should Be    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_SELECTUNSELECTALL_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LBL_SELECTUNSELECTALL_TH}

	
	Check Active For Projects    ${EMPLOYEEMANAGEMENTINFORMATION_ADDEDIT_CHK_PROPERTYNAME_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_ADDEDIT_LBL_PROPERTYNAME_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_ADDEDIT_CHK_BUILDINGNAME_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_ADDEDIT_LBL_BUILDINGNAME_LOCATOR}        


	#Varify Screen : Cancel
	Wait Until Contains Element Text Should Be    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_BTN_CANCEL_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_BTN_CANCEL_TH}

	#Varify Screen : Save
	Wait Until Contains Element Text Should Be    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_BTN_SAVE_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_BTN_SAVE_TH}

Verify screen : Firstname legth 255
# maxlength="255"
	Wait Should Contain Get Element Attribute    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_TXT_FIRSTNAME_LOCATOR}    ${ATTRIBUTE_MAXLENGTH}    ${DEFAULT_TXT_MAXLENGTH_255}

	

Verify screen : Lastname legth 255
# maxlength="255"
	Wait Should Contain Get Element Attribute    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_TXT_LASTNAME_LOCATOR}    ${ATTRIBUTE_MAXLENGTH}    ${DEFAULT_TXT_MAXLENGTH_255}

Verify screen : Phone number legth 10
# maxlength="10"
	Wait Should Contain Get Element Attribute    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_TXT_PHONENUMBER_LOCATOR}    ${ATTRIBUTE_MAXLENGTH}    ${DEFAULT_TXT_MAXLENGTH_10}


	
	#capture page screenshot
	Selenium2Library.Capture Page Screenshot    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_M32_1_0_2_000_SCREENSHOT}
	
################### Close Browser ###################
    [Teardown]    Close Browser
	