*** Settings ***
Resource    ../../../../variables/Variables.robot    
Resource    ../../../../keyword/Keyword.robot
	
*** Test Cases ***
################### Login ###################
M1_0_1_8_001_Login_Success_VerifyScreenPrivacyPolicy   
    [Documentation]    Step is :    
	...    1. open link : https://login.smartcondo.net/en 
	...    2. input data 
	...    3. click sign in button	

	[Setup]    Check Verify screen page Login
	
	#username
	Wait Until Contains Input Text    ${LOGIN_TXT_USERNAME_LOCATOR}    ${VALUE_USERNAME_FIRSTLOGIN}
	#password
	Wait Until Contains Input Text    ${LOGIN_TXT_PASSWORD_LOCATOR}    ${VALUE_PASSWORD_FIRSTLOGIN}
	
    #Click login button	
    Click Element Page    ${LOGIN_BTN_SIGNIN_LOCATOR}	
    
	#Terms and Conditions Header
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_HEADER_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_HEADER_TH} 
	
	#Privacy Policy
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_PRIVACYPOLICY_LOCATOR}    ${LOGIN_LBL_PRIVACYPOLICY_TH} 
	#Privacy Policy Detail
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_PRIVACYPOLICY_DETAIL_LOCATOR}    ${LOGIN_LBL_PRIVACYPOLICY_DETAIL_TH} 
	
	#Terms and Conditions
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_TH} 
	
	#1.Data Controller
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_1_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_1_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_1_DETAIL_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_1_DETAIL_TH} 
	
	#2.What is Personal Data?
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_2_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_2_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_2_DETAIL_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_2_DETAIL_TH} 
	
	#3.Personal Data that the company collects
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_3_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_3_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_1_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_1_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_2_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_2_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_3_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_3_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_4_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_4_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_5_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_5_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_6_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_6_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_7_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_7_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_8_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_3_DETAIL_8_TH} 
	
	#4.The sources of Personal Data
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_4_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_4_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_1_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_1_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_2_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_2_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_3_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_3_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_4_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_4_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_5_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_5_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_6_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_6_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_7_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_7_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_8_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_4_DETAIL_8_TH} 
		
	#5.The purposes for data collection or Personal Data disclosure
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_5_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_1_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_1_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_2_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_2_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_3_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_3_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_4_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_4_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_5_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_5_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_6_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_6_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_7_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_7_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_8_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_8_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_9_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_9_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_10_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_10_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_11_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_11_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_12_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_12_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_13_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_13_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_14_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_14_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_15_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_15_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_16_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_16_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_17_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_5_DETAIL_17_TH} 
	
	#6.Personal Data processing
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_6_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_6_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_6_DETAIL_1_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_6_DETAIL_1_TH} 
    Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_6_DETAIL_2_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_6_DETAIL_2_TH} 

	#7.Storage of data and data retention period
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_7_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_7_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_7_DETAIL_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_7_DETAIL_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_7_DETAIL_1_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_7_DETAIL_1_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_7_DETAIL_2_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_7_DETAIL_2_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_7_DETAIL_3_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_7_DETAIL_3_TH} 
	
	#8.Data Subject Rights
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_8_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_1_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_1_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_2_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_2_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_3_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_3_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_4_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_4_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_5_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_5_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_6_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_6_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_7_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_7_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_8_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_8_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_9_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_9_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_10_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_10_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_11_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_8_DETAIL_11_TH} 
	
	#9.Consequences of consent withdrawal
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_9_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_9_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_9_DETAIL_1_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_9_DETAIL_1_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_9_DETAIL_2_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_9_DETAIL_2_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_9_DETAIL_3_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_9_DETAIL_3_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_9_DETAIL_4_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_9_DETAIL_4_TH} 
	
	#10.In case of the objection against Personal Data collection
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_10_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_10_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_10_DETAIL_1_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_10_DETAIL_1_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_10_DETAIL_2_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_10_DETAIL_2_TH} 
	
	#11.Marketing activities and campaigns
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_11_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_11_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_11_DETAIL_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_11_DETAIL_TH} 
	
	#12.Privacy Policy from other websites
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_12_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_12_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_12_DETAIL_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_12_DETAIL_TH} 
	
	#13.Changes to this Privacy Policy
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_13_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_13_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_13_DETAIL_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_13_DETAIL_TH} 
	
	#14.Terms of Use
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_14_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_14_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_1_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_1_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_2_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_2_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_3_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_3_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_4_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_4_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_5_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_5_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_6_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_6_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_7_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_7_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_8_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_14_DETAIL_8_TH} 
	
	#15.Contact information
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_15_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_15_TH} 
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_15_DETAIL_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_15_DETAIL_TH}
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_15_DETAIL_1_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_15_DETAIL_1_TH}
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_15_DETAIL_2_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_15_DETAIL_2_TH}
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_15_DETAIL_3_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_15_DETAIL_3_TH}
	Wait Until Contains Get Text Split String Join    ${LOGIN_LBL_TERMSANDCONDITIONS_15_DETAIL_4_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_15_DETAIL_4_TH}

	#checkbox
	Wait Until Contains Element Should Be Visible    ${LOGIN_CHK_TERMSANDCONDITIONS_LOCATOR}
	Wait Until Contains Element Text Should Be    ${LOGIN_LBL_TERMSANDCONDITIONS_LOCATOR}    ${LOGIN_LBL_TERMSANDCONDITIONS_TH} 
	
	#Submit button
	Wait Until Contains Element Text Should Be    ${LOGIN_BTN_TERMSANDCONDITIONS_SUBMIT_LOCATOR}    ${LOGIN_BTN_TERMSANDCONDITIONS_SUBMIT_TH} 
	
	#capture page screenshot
	Selenium2Library.Capture Page Screenshot    ${LOGIN_M1_0_1_8_001_SUCCESS_SCREENSHOT}

################### Close Browser ###################
    [Teardown]    Close Browser 