*** Variables ***
############## For Account Admin Page ##############
${EXCEL_PROPERTY_IMPORT_FILENAME}    Import โครงการ.xlsx
${EXCEL_PROPERTY_IMPORT_FILENAME_EDIT}    Import โครงการ_edit.xlsx
${EXCEL_PROPERTY_IMPORT_COLNUM_1}    1
${EXCEL_PROPERTY_IMPORT_COLNUM_2}    2
${EXCEL_PROPERTY_IMPORT_ROWNUM}    1
${EXCEL_PROPERTY_IMPORT_MAXNUM_3}    3
${EXCEL_PROPERTY_IMPORT_MAXNUM_30}    30
${EXCEL_PROPERTY_IMPORT_SHEETNAME}    ข้อมูลโครงการ