*** Variables ***
################################################################-- Bank account information --################################################################
#Create button
${BANKACCOUNTINFORMATION_BTN_CREATE_TH}    เพิ่ม
${BANKACCOUNTINFORMATION_BTN_CREATE_EN}    Create
${BANKACCOUNTINFORMATION_BTN_CREATE_LOCATOR}    id=btnCreate

${BANKACCOUNTINFORMATION_BTN_MORE_LOCATOR}    id=btnMore1
${BANKACCOUNTINFORMATION_LBL_VIEW_TH}    ดู
${BANKACCOUNTINFORMATION_LBL_VIEW_EN}    View
${BANKACCOUNTINFORMATION_LBL_VIEW_TH_LOCATOR}    css=div[class="ant-tooltip-inner ng-tns-c438-11"]
${BANKACCOUNTINFORMATION_LBL_VIEW_EN_LOCATOR}    css=div[class="ant-tooltip-inner ng-tns-c438-13"]
${BANKACCOUNTINFORMATION_BTN_VIEW_LOCATOR}    id=btnView1 
${BANKACCOUNTINFORMATION_LBL_EDIT_TH}    แก้ไข
${BANKACCOUNTINFORMATION_LBL_EDIT_EN}    Edit
${BANKACCOUNTINFORMATION_LBL_EDIT_TH_LOCATOR}    css=div[class="ant-tooltip-inner ng-tns-c438-12"]
${BANKACCOUNTINFORMATION_LBL_EDIT_EN_LOCATOR}    css=div[class="ant-tooltip-inner ng-tns-c438-14"]
${BANKACCOUNTINFORMATION_BTN_EDIT_LOCATOR}    id=btnEdit1
${BANKACCOUNTINFORMATION_LBL_DELETE_TH}    ลบ
${BANKACCOUNTINFORMATION_LBL_DELETE_EN}    Delete
${BANKACCOUNTINFORMATION_LBL_DELETE_TH_LOCATOR}    css=div[class="ant-tooltip-inner ng-tns-c438-13"]
${BANKACCOUNTINFORMATION_LBL_DELETE_EN_LOCATOR}    css=div[class="ant-tooltip-inner ng-tns-c438-15"]
${BANKACCOUNTINFORMATION_BTN_DELETE_LOCATOR}    id=btnDelete1

# ${BANKACCOUNTINFORMATION_BTN_CLOSE_LOCATOR}    id=btnBankAccountInformationClose
${BANKACCOUNTINFORMATION_BTN_CLOSE_LOCATOR}    class=ant-modal-close-x

${BANKACCOUNTINFORMATION_BTN_20}    20
${BANKACCOUNTINFORMATION_BTN_20_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[1]/div[1]
${BANKACCOUNTINFORMATION_BTN_50}    50
${BANKACCOUNTINFORMATION_BTN_50_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[1]/div[2]
${BANKACCOUNTINFORMATION_BTN_100}    100
${BANKACCOUNTINFORMATION_BTN_100_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[1]/div[3]
${BANKACCOUNTINFORMATION_BTN_1000}    1000
${BANKACCOUNTINFORMATION_BTN_1000_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[1]/div[4]
${BANKACCOUNTINFORMATION_LBL_PagesXFromY_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[2]/div[1]
${BANKACCOUNTINFORMATION_ICON_ARRORWLEFT_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[2]/div[2]
${BANKACCOUNTINFORMATION_LBL_PAGE_1}    1
${BANKACCOUNTINFORMATION_LBL_PAGE_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[2]/div[3]
${BANKACCOUNTINFORMATION_ICON_ARRORWRIGHT_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[2]/div[4]

#-------------------------------------------- Search Bank account information --------------------------------------------#
############## Header ############## 
#Bank account information Header
${BANKACCOUNTINFORMATION_SEARCH_LBL_BANKACCOUNTINFORMATION_HEADER_TH}    จัดการบัญชีธนาคาร 
${BANKACCOUNTINFORMATION_SEARCH_LBL_BANKACCOUNTINFORMATION_HEADER_EN}    Bank Account Management
${BANKACCOUNTINFORMATION_SEARCH_LBL_BANKACCOUNTINFORMATION_HEADER_LOCATOR}    xpath=/html/body/app-root/app-layouts/div/app-account-setting/div[1]/div/div/h3
#Bank account information
${BANKACCOUNTINFORMATION_SEARCH_LBL_BANKACCOUNTINFORMATION_TH}    จัดการบัญชีธนาคาร 
${BANKACCOUNTINFORMATION_SEARCH_LBL_BANKACCOUNTINFORMATION_EN}    Bank Account Management
${BANKACCOUNTINFORMATION_SEARCH_LBL_BANKACCOUNTINFORMATION_LOCATOR}    id=lblBankAccountManagementHeaderPage

#Bank Account Name
${BANKACCOUNTINFORMATION_SEARCH_LBL_BANKACCOUNTNAME_TH}    ชื่อบัญชี
${BANKACCOUNTINFORMATION_SEARCH_LBL_BANKACCOUNTNAME_EN}    Bank Account Name
${BANKACCOUNTINFORMATION_SEARCH_LBL_BANKACCOUNTNAME_LOCATOR}    id=lblBankAccountNameSearch
${BANKACCOUNTINFORMATION_SEARCH_INPUT_BANKACCOUNTNAME_LOCATOR}    id=input_txtBankAccountName
${BANKACCOUNTINFORMATION_SEARCH_TXT_BANKACCOUNTNAME_LOCATOR}    id=txtBankAccountName

#Bank Account Number / PromptPay Number
${BANKACCOUNTINFORMATION_SEARCH_LBL_BANKACCOUNTNUMBERPROMPTPAYNUMBER_TH}    เลขที่บัญชี/เลขที่พร้อมเพย์
${BANKACCOUNTINFORMATION_SEARCH_LBL_BANKACCOUNTNUMBERPROMPTPAYNUMBER_EN}    Bank Account Number / Pr...
${BANKACCOUNTINFORMATION_SEARCH_LBL_BANKACCOUNTNUMBERPROMPTPAYNUMBER_LOCATOR}    id=lblBankAccountNumberPromptPayNumberSearch
${BANKACCOUNTINFORMATION_SEARCH_INPUT_BANKACCOUNTNUMBERPROMPTPAYNUMBER_LOCATOR}    id=input_txtBankAccountNumberPromptPayNumber
${BANKACCOUNTINFORMATION_SEARCH_TXT_BANKACCOUNTNUMBERPROMPTPAYNUMBER_LOCATOR}    id=txtBankAccountNumberPromptPayNumber
#Status
${BANKACCOUNTINFORMATION_SEARCH_LBL_STATUS_TH}    สถานะ
${BANKACCOUNTINFORMATION_SEARCH_LBL_STATUS_EN}    Status
${BANKACCOUNTINFORMATION_SEARCH_LBL_STATUS_LOCATOR}    id=lblStatusSearch
${BANKACCOUNTINFORMATION_SEARCH_DDL_STATUS_PLACEHOLDER_VALUE}    2
${BANKACCOUNTINFORMATION_SEARCH_DDL_STATUS_PLACEHOLDER_LOCATOR}    css=#ddlStatusSearch div[class="dx-placeholder dx-state-invisible"]
${BANKACCOUNTINFORMATION_SEARCH_DDL_STATUS_LOCATOR}    id=ddlStatusSearch 
${BANKACCOUNTINFORMATION_SEARCH_DDL_STATUS_LIST_LOCATOR}    xpath=/html/body/div/div/div/div/div[1]/div/div[1]/div[2]/div[replace_indexList]/div
${BANKACCOUNTINFORMATION_SEARCH_DDL_STATUS_CLASS_LOCATOR}    class=dx-list-item-content
@{BANKACCOUNTINFORMATION_SEARCH_DDL_STATUS_TH_VALUE}    ทั้งหมด    ไม่ใช้งาน    ใช้งาน
@{BANKACCOUNTINFORMATION_SEARCH_DDL_STATUS_EN_VALUE}    All    Inactive    Active

#Search
${BANKACCOUNTINFORMATION_SEARCH_BTN_SEARCH_TH}    ค้นหา
${BANKACCOUNTINFORMATION_SEARCH_BTN_SEARCH_EN}    Search
${BANKACCOUNTINFORMATION_SEARCH_BTN_SEARCH_LOCATOR}    id=btnSearch
#Clear
${BANKACCOUNTINFORMATION_SEARCH_BTN_CLEAR_TH}    คืนค่า
${BANKACCOUNTINFORMATION_SEARCH_BTN_CLEAR_EN}    Clear
${BANKACCOUNTINFORMATION_SEARCH_BTN_CLEAR_LOCATOR}    id=btnClear

############################ 
############## Table ############## 
#No
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_NO_TH}    ลำดับ
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_NO_EN}    No.
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_NO_LOCATOR}    id=dx-col-15
#Bank account
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_BANKACCOUNT_TH}    บัญชีธนาคาร
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_BANKACCOUNT_EN}    Bank account
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_BANKACCOUNT_LOCATOR}    id=dx-col-16
#Account types
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_ACCOUNTTYPES_TH}    ประเภทบัญชี
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_ACCOUNTTYPES_EN}    Account types
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_ACCOUNTTYPES_LOCATOR}    id=dx-col-17
#Account name
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_ACCOUNTNAME_TH}    ชื่อบัญชี
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_ACCOUNTNAME_EN}    Account name
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_ACCOUNTNAME_LOCATOR}    id=dx-col-18
#Bank Account Number / PromptPay Number
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_BANKACCOUNTNUMBERPROMPTPAYNUMBER_TH}    เลขที่บัญชี/เลขที่พร้อมเพย์
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_BANKACCOUNTNUMBERPROMPTPAYNUMBER_EN}    Bank Account Number / PromptPay Number
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_BANKACCOUNTNUMBERPROMPTPAYNUMBER_LOCATOR}    id=dx-col-19
#Status
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_STATUS_TH}    สถานะ
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_STATUS_EN}    Status
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_STATUS_LOCATOR}    id=dx-col-20
#No Data
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_NODATA_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[6]/span
#For check value table
${BANKACCOUNTINFORMATION_SEARCH_LBL_RESULT_DATA_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[6]/div/div/div[1]/div/table/tbody/tr[row]/td[col]
${BANKACCOUNTINFORMATION_SEARCH_NUMCOL}    6
@{BANKACCOUNTINFORMATION_SEARCH_LBL_FIELD_HEADER_TABLE_VALUE_TH}    no    banknameTh    bankAccountType    bankAccountName    bankAccountPromptPayNumber    status
@{BANKACCOUNTINFORMATION_SEARCH_LBL_FIELD_HEADER_TABLE_VALUE_EN}    no    banknameEn    bankAccountType    bankAccountName    bankAccountPromptPayNumber    status

############################ 
#-------------------------------------------- View Bank account --------------------------------------------#
#View Bank Account Information
${BANKACCOUNTINFORMATION_VIEW_LBL_VIEWBANKACCOUNTINFORMATION_TH}    ดูข้อมูลบัญชีธนาคาร 
${BANKACCOUNTINFORMATION_VIEW_LBL_VIEWBANKACCOUNTINFORMATION_EN}    View Bank Account Information
${BANKACCOUNTINFORMATION_VIEW_LBL_VIEWBANKACCOUNTINFORMATION_LOCATOR}    id=lblViewBankAccountInformation
#Bank
${BANKACCOUNTINFORMATION_VIEW_LBL_BANK_TH}    บัญชีธนาคาร 
${BANKACCOUNTINFORMATION_VIEW_LBL_BANK_EN}    Bank
${BANKACCOUNTINFORMATION_VIEW_LBL_BANK_LOCATOR}    id=lblBankView
${BANKACCOUNTINFORMATION_VIEW_LBD_BANK_LOCATOR}    id=lbdBankView
#Bank Account Type
${BANKACCOUNTINFORMATION_VIEW_LBL_BANKACCOUNTTYPE_TH}    ประเภทบัญชี 
${BANKACCOUNTINFORMATION_VIEW_LBL_BANKACCOUNTTYPE_EN}    Bank Account Type
${BANKACCOUNTINFORMATION_VIEW_LBL_BANKACCOUNTTYPE_LOCATOR}    id=lblBankAccountTypeView
${BANKACCOUNTINFORMATION_VIEW_LBD_BANKACCOUNTTYPE_LOCATOR}    id=lbdBankAccountTypeView
#Branch
${BANKACCOUNTINFORMATION_VIEW_LBL_BRANCH_TH}    สาขา
${BANKACCOUNTINFORMATION_VIEW_LBL_BRANCH_EN}    Branch
${BANKACCOUNTINFORMATION_VIEW_LBL_BRANCH_LOCATOR}    id=lblBranchView
${BANKACCOUNTINFORMATION_VIEW_LBD_BRANCH_LOCATOR}    id=lbdBranchView
#Bank Account Name
${BANKACCOUNTINFORMATION_VIEW_LBL_ACCOUNTNAME_TH}    ชื่อบัญชี
${BANKACCOUNTINFORMATION_VIEW_LBL_ACCOUNTNAME_EN}    Bank Account Name
${BANKACCOUNTINFORMATION_VIEW_LBL_ACCOUNTNAME_LOCATOR}    id=lblAccountNameView
${BANKACCOUNTINFORMATION_VIEW_LBD_ACCOUNTNAME_LOCATOR}    id=lbdAccountNameView
#Bank Account/PromptPay Number
${BANKACCOUNTINFORMATION_VIEW_LBL_ACCOUNTPROMPTPAYNUMBER_TH}    เลขที่บัญชี/เลขที่พร้อมเพย์
${BANKACCOUNTINFORMATION_VIEW_LBL_ACCOUNTPROMPTPAYNUMBER_EN}    Bank Account/PromptPay Number
${BANKACCOUNTINFORMATION_VIEW_LBL_ACCOUNTPROMPTPAYNUMBER_LOCATOR}    id=lblAccountPromptPayNumberView
${BANKACCOUNTINFORMATION_VIEW_LBD_ACCOUNTPROMPTPAYNUMBER_LOCATOR}    id=lbdAccountPromptPayNumberView
#Status
${BANKACCOUNTINFORMATION_VIEW_LBL_STATUS_TH}    สถานะ
${BANKACCOUNTINFORMATION_VIEW_LBL_STATUS_EN}    Status
${BANKACCOUNTINFORMATION_VIEW_LBL_STATUS_LOCATOR}    id=lblStatusView
${BANKACCOUNTINFORMATION_VIEW_LBD_STATUS_LOCATOR}    id=lbdStatusView
#Operate Type 
${BANKACCOUNTINFORMATION_VIEW_LBL_OPERATETYPE_TH}    ประเภทการใช้งาน
${BANKACCOUNTINFORMATION_VIEW_LBL_OPERATETYPE_EN}    Operate Type
${BANKACCOUNTINFORMATION_VIEW_LBL_OPERATETYPE_LOCATOR}    id=lblOperateTypeView
${BANKACCOUNTINFORMATION_VIEW_LBD_OPERATETYPE_LOCATOR}    id=lbdOperateTypeView
#Remark 
${BANKACCOUNTINFORMATION_VIEW_LBL_REMARK_TH}    หมายเหตุ
${BANKACCOUNTINFORMATION_VIEW_LBL_REMARK_EN}    Remark
${BANKACCOUNTINFORMATION_VIEW_LBL_REMARK_LOCATOR}    id=lblRemarkView
${BANKACCOUNTINFORMATION_VIEW_LBD_REMARK_LOCATOR}    id=lbdRemarkView
#Active For Projects
${BANKACCOUNTINFORMATION_VIEW_LBL_ACTIVEFORPROJECTS_TH}    ใช้งานสำหรับโครงการ
${BANKACCOUNTINFORMATION_VIEW_LBL_ACTIVEFORPROJECTS_EN}    Active For Projects
${BANKACCOUNTINFORMATION_VIEW_LBL_ACTIVEFORPROJECTS_LOCATOR}    id=lblActiveForView
#Project of Building
${BANKACCOUNTINFORMATION_VIEW_LBL_PROPERTYNAME_LOCATOR}    id=lblPropertyNameView1
${BANKACCOUNTINFORMATION_VIEW_CHK_PROPERTYNAME_LOCATOR}    id=chkPropertyNameView1
${BANKACCOUNTINFORMATION_VIEW_LBL_BUILDINGNAME_LOCATOR}    id=lblBuildingNameView19
${BANKACCOUNTINFORMATION_VIEW_CHK_BUILDINGNAME_LOCATOR}    id=chkBuildingNameView19

#-------------------------------------------- Add Edit Bank account --------------------------------------------#
#Create Bank Account Information
${BANKACCOUNTINFORMATION_ADD_LBL_CREATEBANKACCOUNTINFORMATION_TH}    เพิ่มข้อมูลบัญชีธนาคาร 
${BANKACCOUNTINFORMATION_ADD_LBL_CREATEBANKACCOUNTINFORMATION_EN}    Create Bank Account Information
${BANKACCOUNTINFORMATION_ADD_LBL_CREATEBANKACCOUNTINFORMATION_LOCATOR}    id=lblCreateBankAccountInformation

#Edit Bank Account Information
${BANKACCOUNTINFORMATION_EDIT_LBL_EDITBANKACCOUNTINFORMATION_TH}    แก้ไขข้อมูลบัญชีธนาคาร 
${BANKACCOUNTINFORMATION_EDIT_LBL_EDITBANKACCOUNTINFORMATION_EN}    Edit Bank Account Information
${BANKACCOUNTINFORMATION_EDIT_LBL_EDITBANKACCOUNTINFORMATION_LOCATOR}    id=lblEditBankAccountInformation

#Bank *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_BANK_TH}    บัญชีธนาคาร *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_BANK_EN}    Bank *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_BANK_LOCATOR}    id=lblBankCreateEdit
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_BANK_PLACEHOLDER_LOCATOR}    css=#ddlBank div[class="dx-placeholder"]
${BANKACCOUNTINFORMATION_ADDEDIT_TXT_BANK_LOCATOR}    id=input_ddlBank
${BANKACCOUNTINFORMATION_ADDEDIT_TXT_BANK_PLEASEINPUTDATA_LOCATOR}    xpath=//*[@id="ddlBank"]/div[2]/div/div
${BANKACCOUNTINFORMATION_ADDEDIT_DDL_BANK_LOCATOR}    id=ddlBank
# ${BANKACCOUNTINFORMATION_ADDEDIT_DDL_BANK_LIST_LOCATOR}    xpath=/html/body/div/div/div/div/div[1]/div/div[1]/div[2]/div[replace_indexList]/div
${BANKACCOUNTINFORMATION_ADDEDIT_DDL_BANK_LIST_LOCATOR}    xpath=/html/body/div/div/div/div/div[1]/div/div/div[replace_indexList]/div[2]
${BANKACCOUNTINFORMATION_ADDEDIT_DDL_BANK_CLASS_LOCATOR}    class=dx-list-item-content
# @{BANKACCOUNTINFORMATION_ADDEDIT_DDL_BANK_TH_VALUE}    ธนาคารยูโอบี    พร้อมเพย์    ธนาคารกรุงเทพ    ธนาคารกสิกรไทย    ธนาคารออมสิน    ธนาคารกรุงไทย    ธนาคารไทยพาณิชย์    ธนาคารทหารไทย    ธนาคารทิสโก้    ธนาคารธนชาต    ธนาคารกรุงศรีอยุธยา    ธนาคารเกียรตินาคิน    ธนาคารซีไอเอ็มบีไทย    ธนาคารอาคารสงเคราะห์    ธนาคารอิสลามแห่งประเทศไทย    ธนาคารสแตนดาร์ดชาร์เตอร์ด    ธนาคารไทยเครดิตเพื่อรายย่อย    ธนาคารแลนด์ แอนด์ เฮาส์    ธนาคารไอซีบีซี (ไทย)    ธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร    ธนาคารเพื่อการส่งออกและนำเข้าแห่งประเทศไทย    ธนาคารพัฒนาวิสาหกิจขนาดกลางและขนาดย่อมแห่งประเทศไทย
# @{BANKACCOUNTINFORMATION_ADDEDIT_DDL_BANK_EN_VALUE}    United Overseas Bank    Prompt Pay    Bangkok Bank    Kasikorn Bank    Government Servings Bank    Krung Thai Bank    Siam Commercial Bank    TMB Bank    TISCO Bank    Thanachart Bank    Krungsri Bank    Kiatnakin Bank    CIMBTHAI    Covernment Housing Bank    Islamic Bank of thailand        Standard Chartered Bank Thai    Thai Credit Retail Bank        LH Bank    ICBC Thai Bank        Bank for Agriculture and Agricultural Cooperratives    Export-Import Bank of Thailand    SME Bank
#Bank Account Type *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_BANKACCOUNTTYPE_TH}    ประเภทบัญชี *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_BANKACCOUNTTYPE_EN}    Bank Account Type *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_BANKACCOUNTTYPE_LOCATOR}    id=lblBankAccountTypeCreateEdit
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_BANKACCOUNTTYPE_PLACEHOLDER_LOCATOR}    css=#ddlBankAccountType div[class="dx-placeholder"]
${BANKACCOUNTINFORMATION_ADDEDIT_TXT_BANKACCOUNTTYPE_LOCATOR}    id=input_ddlBankAccountType
${BANKACCOUNTINFORMATION_ADDEDIT_TXT_BANKACCOUNTTYPE_PLEASEINPUTDATA_LOCATOR}    xpath=//*[@id="ddlBankAccountType"]/div[2]/div/div
${BANKACCOUNTINFORMATION_ADDEDIT_DDL_BANKACCOUNTTYPE_LOCATOR}    id=ddlBankAccountType
${BANKACCOUNTINFORMATION_ADDEDIT_DDL_BANKACCOUNTTYPE_LIST_LOCATOR}    xpath=/html/body/div/div/div/div/div[1]/div/div[1]/div[2]/div[replace_indexList]/div
${BANKACCOUNTINFORMATION_ADDEDIT_DDL_BANKACCOUNTTYPE_CLASS_LOCATOR}    class=dx-list-item-content 
@{BANKACCOUNTINFORMATION_ADDEDIT_DDL_BANKACCOUNTTYPE_TH_VALUE}    เงินฝากออมทรัพย์    เงินฝากกระแสรายวัน    ฝากประจำ   
@{BANKACCOUNTINFORMATION_ADDEDIT_DDL_BANKACCOUNTTYPE_EN_VALUE}    Savings    Current deposit    Fixed deposit
#Branch
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_BRANCH_TH}    สาขา
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_BRANCH_EN}    Branch
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_BRANCH_LOCATOR}    id=lblBranchCreateEdit
${BANKACCOUNTINFORMATION_ADDEDIT_TXT_BRANCH_LOCATOR}    id=input_txtBranch
#Bank Account Name *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_ACCOUNTNAME_TH}    ชื่อบัญชี *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_ACCOUNTNAME_EN}    Bank Account Name *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_ACCOUNTNAME_LOCATOR}    id=lblAccountNameCreateEdit
${BANKACCOUNTINFORMATION_ADDEDIT_TXT_ACCOUNTNAME_LOCATOR}    id=input_txtAccountName
${BANKACCOUNTINFORMATION_ADDEDIT_TXT_ACCOUNTNAME_PLEASEINPUTDATA_LOCATOR}    xpath=//*[@id="txtAccountName"]/div[2]/div/div
#Bank Account/PromptPay Number *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_ACCOUNTPROMPTPAYNUMBER_TH}    เลขที่บัญชี/เลขที่พร้อมเพย์ *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_ACCOUNTPROMPTPAYNUMBER_EN}    Bank Account/PromptPay Number *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_ACCOUNTPROMPTPAYNUMBER_LOCATOR}    id=lblAccountPromptPayNumberCreateEdit
${BANKACCOUNTINFORMATION_ADDEDIT_TXT_ACCOUNTPROMPTPAYNUMBER_LOCATOR}    id=input_txtAccountPromptPayNumber
${BANKACCOUNTINFORMATION_ADDEDIT_TXT_ACCOUNTPROMPTPAYNUMBER_PLEASEINPUTDATA_LOCATOR}    xpath=//*[@id="txtAccountPromptPayNumber"]/div[2]/div/div
#Status *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_STATUS_TH}    สถานะ *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_STATUS_EN}    Status *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_STATUS_LOCATOR}    id=lblStatusCreateEdit
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_STATUS_PLACEHOLDER_VALUE}    1
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_STATUS_PLACEHOLDER_LOCATOR}    css=#ddlStatus div[class="dx-placeholder dx-state-invisible"]
${BANKACCOUNTINFORMATION_ADDEDIT_TXT_STATUS_LOCATOR}    id=input_ddlStatus
${BANKACCOUNTINFORMATION_ADDEDIT_DDL_STATUS_LOCATOR}    id=ddlStatus
${BANKACCOUNTINFORMATION_ADDEDIT_DDL_STATUS_LIST_LOCATOR}    xpath=/html/body/div/div/div/div/div[1]/div/div[1]/div[2]/div[replace_indexList]/div
${BANKACCOUNTINFORMATION_ADDEDIT_DDL_STATUS_CLASS_LOCATOR}    class=dx-list-item-content
@{BANKACCOUNTINFORMATION_ADDEDIT_DDL_STATUS_TH_VALUE}    ไม่ใช้งาน    ใช้งาน
@{BANKACCOUNTINFORMATION_ADDEDIT_DDL_STATUS_EN_VALUE}    Inactive    Active
#Operate Type *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_OPERATETYPE_TH}    ประเภทการใช้งาน *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_OPERATETYPE_EN}    Operate Type *
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_OPERATETYPE_LOCATOR}    id=lblOperateTypeCreateEdit
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_OPERATETYPE_PLACEHOLDER_VALUE}    1
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_OPERATETYPE_PLACEHOLDER_LOCATOR}    css=#ddlOperateType div[class="dx-placeholder dx-state-invisible"]
${BANKACCOUNTINFORMATION_ADDEDIT_TXT_OPERATETYPE_LOCATOR}    id=input_ddlOperateType
${BANKACCOUNTINFORMATION_ADDEDIT_DDL_OPERATETYPE_LOCATOR}    id=ddlOperateType
${BANKACCOUNTINFORMATION_ADDEDIT_DDL_OPERATETYPE_LIST_LOCATOR}    xpath=/html/body/div/div/div/div/div[1]/div/div[1]/div[2]/div[replace_indexList]/div
${BANKACCOUNTINFORMATION_ADDEDIT_DDL_OPERATETYPE_CLASS_LOCATOR}    class=dx-list-item-content
@{BANKACCOUNTINFORMATION_ADDEDIT_DDL_OPERATETYPE_TH_VALUE}    รับชำระ    จ่ายชำระ    รับและจ่ายชำระ
@{BANKACCOUNTINFORMATION_ADDEDIT_DDL_OPERATETYPE_EN_VALUE}    Receive payment    Paid    Receive and pay deposit
#Remark 
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_REMARK_TH}    หมายเหตุ
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_REMARK_EN}    Remark
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_REMARK_LOCATOR}    id=lblRemarkCreateEdit
${BANKACCOUNTINFORMATION_ADDEDIT_TXTAREA_REMARK_LOCATOR}    id=input_txtareaRemark

#Active For Projects
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_ACTIVEFORPROJECTS_TH}    ใช้งานสำหรับโครงการ
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_ACTIVEFORPROJECTS_EN}    Active For Projects
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_ACTIVEFORPROJECTS_LOCATOR}    id=lblActiveForProjectsCreateEdit
#Select / Unselect all
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_SELECTUNSELECTALL_TH}    เลือก/ไม่เลือกทั้งหมด
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_SELECTUNSELECTALL_EN}    Select / Unselect all
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_SELECTUNSELECTALL_LOCATOR}    id=lblSelectUnselectAllCreateEdit
${BANKACCOUNTINFORMATION_ADDEDIT_CHK_SELECTUNSELECTALL_LOCATOR}    id=chkSelectUnselectAllCreateEdit
#Project of Building
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_PROPERTYNAME_LOCATOR}    id=lblPropertyNameCreateEdit
${BANKACCOUNTINFORMATION_ADDEDIT_CHK_PROPERTYNAME_LOCATOR}    id=chkPropertyNameCreateEdit
${BANKACCOUNTINFORMATION_ADDEDIT_LBL_BUILDINGNAME_LOCATOR}    id=lblBuildingNameCreateEdit
${BANKACCOUNTINFORMATION_ADDEDIT_CHK_BUILDINGNAME_LOCATOR}    id=chkBuildingNameCreateEdit
#Cancel
${BANKACCOUNTINFORMATION_ADDEDIT_BTN_CANCEL_TH}    ยกเลิก
${BANKACCOUNTINFORMATION_ADDEDIT_BTN_CANCEL_EN}    Cancel
${BANKACCOUNTINFORMATION_ADDEDIT_BTN_CANCEL_LOCATOR}    id=btnCancel
#Save
${BANKACCOUNTINFORMATION_ADDEDIT_BTN_SAVE_TH}    บันทึก
${BANKACCOUNTINFORMATION_ADDEDIT_BTN_SAVE_EN}    Save
${BANKACCOUNTINFORMATION_ADDEDIT_BTN_SAVE_LOCATOR}    id=btnSave
################################################################################################################################
################################################################-- Value --################################################################
#-------------------------------------------- data Create --------------------------------------------#
#Bank *
${BANKACCOUNTINFORMATION_BANK_TH_VALUE1}    ธนาคารกรุงเทพ
${BANKACCOUNTINFORMATION_BANK_EN_VALUE1}    Bangkok Bank
${BANKACCOUNTINFORMATION_BANKID_VALUE1}    1
${BANKACCOUNTINFORMATION_BANK_TH_VALUE2}    ธนาคารกรุงไทย
${BANKACCOUNTINFORMATION_BANK_EN_VALUE2}    Krung Thai Bank
${BANKACCOUNTINFORMATION_BANKID_VALUE2}    4
#Bank Account Type *
${BANKACCOUNTINFORMATION_BANKACCOUNTTYPE_TH_VALUE1}    ฝากประจำ   
${BANKACCOUNTINFORMATION_BANKACCOUNTTYPE_EN_VALUE1}    Fixed deposit
${BANKACCOUNTINFORMATION_BANKACCOUNTTYPEID_VALUE1}    3
${BANKACCOUNTINFORMATION_BANKACCOUNTTYPE_TH_VALUE2}    เงินฝากกระแสรายวัน   
${BANKACCOUNTINFORMATION_BANKACCOUNTTYPE_EN_VALUE2}    Current deposit
${BANKACCOUNTINFORMATION_BANKACCOUNTTYPEID_VALUE2}    2
#Branch
${BANKACCOUNTINFORMATION_BRANCH_VALUE1}    สาขา1
${BANKACCOUNTINFORMATION_BRANCH_VALUE2}    None
#Bank Account Name *
${BANKACCOUNTINFORMATION_ACCOUNTNAME_VALUE1}    บัญชี1
${BANKACCOUNTINFORMATION_ACCOUNTNAME_VALUE2}    บัญชี2
#Bank Account/PromptPay Number *
${BANKACCOUNTINFORMATION_ACCOUNTPROMPTPAYNUMBER_VALUE1}   111111111112
${BANKACCOUNTINFORMATION_ACCOUNTPROMPTPAYNUMBER_VALUE2}   111111111113
#Status *
${BANKACCOUNTINFORMATION_STATUS_TH_VALUE1}    ใช้งาน
${BANKACCOUNTINFORMATION_STATUS_EN_VALUE1}    Active
${BANKACCOUNTINFORMATION_STATUSID_VALUE1}    1
${BANKACCOUNTINFORMATION_STATUS_TH_VALUE2}    ไม่ใช้งาน
${BANKACCOUNTINFORMATION_STATUS_EN_VALUE2}    Inactive
${BANKACCOUNTINFORMATION_STATUSID_VALUE2}    0
#Operate Type *
${BANKACCOUNTINFORMATION_OPERATETYPE_TH_VALUE1}    รับและจ่ายชำระ
${BANKACCOUNTINFORMATION_OPERATETYPE_EN_VALUE1}    Receive and pay deposit
${BANKACCOUNTINFORMATION_OPERATETYPEID_VALUE1}    3
${BANKACCOUNTINFORMATION_OPERATETYPE_TH_VALUE2}    จ่ายชำระ
${BANKACCOUNTINFORMATION_OPERATETYPE_EN_VALUE2}    Paid
${BANKACCOUNTINFORMATION_OPERATETYPEID_VALUE2}    2
#Remark 
${BANKACCOUNTINFORMATION_REMARK_VALUE1}    หมายเหตุ1
${BANKACCOUNTINFORMATION_REMARK_VALUE2}    None

#Property Building 
${BANKACCOUNTINFORMATION_PROPERTY_TH_VALUE}    SmartRmsCondo B
${BANKACCOUNTINFORMATION_PROPERTY_EN_VALUE}    SmartRmsCondo B
${BANKACCOUNTINFORMATION_BUIBING_TH_VALUE}    ศุภากรเพลส
${BANKACCOUNTINFORMATION_BUIBING_EN_VALUE}    ศุภากรเพลส
@{BANKACCOUNTINFORMATION_PROPERTYID_VALUE}    8
@{BANKACCOUNTINFORMATION_BUIBINGID_VALUE}    19
# @{BANKACCOUNTINFORMATION_PROPERTYID_VALUE}    2    2    2    2    12    13
# @{BANKACCOUNTINFORMATION_BUIBINGID_VALUE}    5    1    15    17    20    21

################################################################-- capture page screenshot --################################################################
#-------------------------------------------- Search --------------------------------------------#	
${BANKACCOUNTINFORMATION_SEARCH_M8_1_0_1_000_ERROR_SCREENSHOT}    M8_1_0_1_000_BankAccountManagement_Error_Search_VerifyResultSearchBankAccount_Screen.png

${BANKACCOUNTINFORMATION_SEARCH_M8_0_1_1_000_SUCCESS_SCREENSHOT}    M8_0_1_1_000_BankAccountManagement_Success_Search_VerifyScreen_Screen.png
${BANKACCOUNTINFORMATION_SEARCH_M8_1_1_1_000_SUCCESS_SCREENSHOT}    M8_1_1_1_000_BankAccountManagement_Success_Search_VerifyAction_Screen.png
#-------------------------------------------- View --------------------------------------------#	
${BANKACCOUNTINFORMATION_VIEW_M8_1_0_5_000_ERROR_SCREENSHOT}    M8_1_0_5_000_BankAccountManagement_Error_View_DataNotFound_ViewBankAccount_Screen.png

${BANKACCOUNTINFORMATION_VIEW_M8_0_1_5_000_SUCCESS_SCREENSHOT}    M8_0_1_5_000_BankAccountManagement_Success_View_VerifyScreen_Screen.png
${BANKACCOUNTINFORMATION_VIEW_M8_1_1_5_000_SUCCESS_SCREENSHOT}    M8_1_1_5_000_BankAccountManagement_Success_View_VerifyAction_Screen.png
#-------------------------------------------- Create --------------------------------------------#	
${BANKACCOUNTINFORMATION_CREATE_M8_0_0_2_000_ERROR_SCREENSHOT}    M8_0_0_2_000_BankAccountManagement_Error_Create_VerifyScreen_Screen.png
${BANKACCOUNTINFORMATION_CREATE_M8_1_0_2_006_ERROR_SCREENSHOT}    M8_1_0_2_006_BankAccountManagement_Error_Create_DataAlreadyExisted_Screen.png

${BANKACCOUNTINFORMATION_CREATE_M8_0_1_2_000_SUCCESS_SCREENSHOT}    M8_0_1_2_000_BankAccountManagement_Success_Create_VerifyScreen_Screen.png
${BANKACCOUNTINFORMATION_CREATE_M8_1_1_2_000_SUCCESS_SCREENSHOT}    M8_1_1_2_000_BankAccountManagement_Success_Create_VerifyAction_Screen.png
#-------------------------------------------- Edit --------------------------------------------#	
${BANKACCOUNTINFORMATION_EDIT_M8_0_0_3_002_ERROR_SCREENSHOT}    M8_0_0_3_002_BankAccountManagement_Error_Edit_VerifyScreen_Screen.png
${BANKACCOUNTINFORMATION_EDIT_M8_1_0_3_000_ERROR_SCREENSHOT}    M8_1_0_3_000_BankAccountManagement_Error_Edit_DataNotFound_ViewBankAccount_Screen.png
${BANKACCOUNTINFORMATION_EDIT_M8_1_0_3_009_ERROR_SCREENSHOT}    M8_1_0_3_009_BankAccountManagement_Error_Edit_DataAlreadyExisted_UpdateBankAccount_Screen.png
${BANKACCOUNTINFORMATION_EDIT_M8_1_0_3_012_ERROR_SCREENSHOT}    M8_1_0_3_012_BankAccountManagement_Error_Edit_DataNotFound_UpdateBankAccount_Screen.png

${BANKACCOUNTINFORMATION_EDIT_M8_0_1_3_000_SUCCESS_SCREENSHOT}    M8_0_1_3_000_BankAccountManagement_Success_Edit_VerifyScreen_Screen.png
${BANKACCOUNTINFORMATION_EDIT_M8_1_1_3_000_SUCCESS_SCREENSHOT}    M8_1_1_3_000_BankAccountManagement_Success_Edit_VerifyAction_Screen.png
#-------------------------------------------- Delete --------------------------------------------#	
${BANKACCOUNTINFORMATION_DELETE_M8_1_0_4_000_ERROR_SCREENSHOT}    M8_1_0_4_000_BankAccountManagement_Error_Delete_DataNotFound_Screen.png

${BANKACCOUNTINFORMATION_DELETE_M8_0_1_4_000_SUCCESS_SCREENSHOT}    M8_0_1_4_000_BankAccountManagement_Success_Delete_VerifyScreen_Screen.png
${BANKACCOUNTINFORMATION_DELETE_M8_1_1_4_000_SUCCESS_SCREENSHOT}    M8_1_1_4_000_BankAccountManagement_Success_Delete_VerifyAction_Screen.png























