*** Variables ***
################################################################-- Check Asset Management information --################################################################

#Add button
${ASSETMANAGEMENTINFORMATION_BTN_ADD_TH}    เพิ่ม
${ASSETMANAGEMENTINFORMATION_BTN_ADD_EN}    Create
${ASSETMANAGEMENTINFORMATION_BTN_ADD_LOCATOR}    id=btnCreate

#Search button
${ASSETMANAGEMENTINFORMATION_BTN_SEARCH_TH}    ค้นหา
${ASSETMANAGEMENTINFORMATION_BTN_SEARCH_EN}    Search
${ASSETMANAGEMENTINFORMATION_BTN_SEARCH_LOCATOR}    id=btnSearch

#Clear button
${ASSETMANAGEMENTINFORMATION_BTN_CLEAR_TH}    คืนค่า
${ASSETMANAGEMENTINFORMATION_BTN_CLEAR_EN}    Clear
${ASSETMANAGEMENTINFORMATION_BTN_CLEAR_LOCATOR}    id=btnClear


#Button page
${ASSETMANAGEMENTINFORMATION_BTN_20}    20
${ASSETMANAGEMENTINFORMATION_BTN_20_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[1]/div[1]
${ASSETMANAGEMENTINFORMATION_BTN_50}    50
${ASSETMANAGEMENTINFORMATION_BTN_50_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[1]/div[2]
${ASSETMANAGEMENTINFORMATION_BTN_100}    100
${ASSETMANAGEMENTINFORMATION_BTN_100_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[1]/div[3]
${ASSETMANAGEMENTINFORMATION_BTN_1000}    1000
${ASSETMANAGEMENTINFORMATION_BTN_1000_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[1]/div[4]

${ASSETMANAGEMENTINFORMATION_LBL_PAGE_1}    1
${ASSETMANAGEMENTINFORMATION_LBL_PAGE_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[2]/div[3]

${ASSETMANAGEMENTINFORMATION_LBL_PagesXFromY_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[2]/div[1]
${ASSETMANAGEMENTINFORMATION_ICON_ARRORWLEFT_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[2]/div[2]
${ASSETMANAGEMENTINFORMATION_ICON_ARRORWRIGHT_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[11]/div[2]/div[4]


#Disable Icon
${ASSETMANAGEMENTINFORMATION_ICON_DISABLE_TH}    ปิดการใช้งาน
${ASSETMANAGEMENTINFORMATION_ICON_DISABLE_EN}    Disable
${ASSETMANAGEMENTINFORMATION_ICON_DISABLE_LOCATOR}    id=btnDisable1
${ASSETMANAGEMENTINFORMATION_LBL_DISABLE_TH_LOCATOR}    xpath=//*[@id="cdk-overlay-1"]/div/div/div[2]
${ASSETMANAGEMENTINFORMATION_LBL_DISABLE_EN_LOCATOR}    css=div[class="ant-tooltip-inner ng-tns-c438-10"]



#Enable Icon
${ASSETMANAGEMENTINFORMATION_ICON_ENABLE_TH}    เปิดการใช้งาน
${ASSETMANAGEMENTINFORMATION_ICON_ENABLE_EN}    Enable
${ASSETMANAGEMENTINFORMATION_ICON_ENABLE_LOCATOR}    id=btnEnable1
${ASSETMANAGEMENTINFORMATION_LBL_ENABLE_TH_LOCATOR}    xpath=//*[@id="cdk-overlay-2"]/div/div/div[2]
${ASSETMANAGEMENTINFORMATION_LBL_ENABLE_EN_LOCATOR}    css=div[class="ant-tooltip-inner ng-tns-c438-12"]



#Edit Icon
${ASSETMANAGEMENTINFORMATION_ICON_EDIT_TH}    แก้ไข
${ASSETMANAGEMENTINFORMATION_ICON_EDIT_EN}    Edit
${ASSETMANAGEMENTINFORMATION_ICON_EDIT_LOCATOR}    id=btnEdit1
${ASSETMANAGEMENTINFORMATION_LBL_EDIT_TH_LOCATOR}    xpath=//*[@id="cdk-overlay-1"]/div/div/div[2]
${ASSETMANAGEMENTINFORMATION_LBL_EDIT_EN_LOCATOR}    css=div[class="ant-tooltip-inner ng-tns-c438-11"]



#Icon X Close
${ASSETMANAGEMENTINFORMATION_BTN_CLOSE_LOCATOR}    class=ant-modal-close-x




#-------------------------------------------- Search Check Asset Management information --------------------------------------------#
############## Header ############## 
#Asset Management information Header
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_ASSETMANAGEMENTINFORMATION_HEADER_TH}    จัดการรายการส่งมอบอุปกรณ์ 
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_ASSETMANAGEMENTINFORMATION_HEADER_EN}    Check Asset Management
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_ASSETMANAGEMENTINFORMATION_HEADER_LOCATOR}    xpath=/html/body/app-root/app-layouts/div/app-account-setting/div[1]/div/div/h3


#Check asset management information
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_ASSETMANAGEMENTINFORMATION_TH}    จัดการรายการส่งมอบอุปกรณ์ 
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_ASSETMANAGEMENTINFORMATION_EN}    Check asset management
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_ASSETMANAGEMENTINFORMATION_LOCATOR}    id=lblAssetManagement


#Status
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_STATUS_TH}    สถานะ 
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_STATUS_EN}    Status
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_STATUS_LOCATOR}    id=lblStatus
${ASSETMANAGEMENTINFORMATION_SEARCH_DDL_STATUS_LOCATOR}    id=ddlStatus
${ASSETMANAGEMENTINFORMATION_SEARCH_DDL_PROPERTYMANAGER_LIST_LOCATOR}    xpath=/html/body/div/div/div/div/div[1]/div/div[1]/div[2]/div[replace_indexList]/div
${ASSETMANAGEMENTINFORMATION_SEARCH_DDL_STATUS_CLASS_LOCATOR}    class=dx-list-item-content
@{ASSETMANAGEMENTINFORMATION_SEARCH_DDL_STATUS_TH_VALUE}    ทั้งหมด    ไม่ใช้งาน    ใช้งาน
@{ASSETMANAGEMENTINFORMATION_SEARCH_DDL_STATUS_EN_VALUE}    All    Inactive    Active



#Status
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_ASSETNAME_TH}    ชื่ออุปกรณ์ 
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_ASSETNAME_EN}    Asset name
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_ASSETNAME_LOCATOR}    id=lblAssetName
${ASSETMANAGEMENTINFORMATION_SEARCH_TXT_ASSETNAME_LOCATOR}    id=txtAssetName

######################################### Table ##################################################### 
#No
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_NO_TH}    ลำดับ
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_NO_EN}    No.
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_NO_LOCATOR}    id=dx-col-11

#Asset name
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_ASSETNAME_TH}    ชื่ออุปกรณ์
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_ASSETNAME_EN}    Asset name
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_ASSETNAME_LOCATOR}    id=dx-col-12

#Remark
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_REMARK_TH}    หมายเหตุ
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_REMARK_EN}    Remark
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_REMARK_LOCATOR}    id=dx-col-13

#Status
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_STATUS_TH}    สถานะการใช้งาน
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_STATUS_EN}    Status
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_STATUS_LOCATOR}    id=dx-col-14


${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_NODATA_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[6]/span
#For check value table
${ASSETMANAGEMENTINFORMATION_SEARCH_LBL_RESULT_DATA_LOCATOR}    xpath=//*[@id="contractListOptions"]/div/div[6]/div/div/div[1]/div/table/tbody/tr[row]/td[col]
@{ASSETMANAGEMENTINFORMATION_SEARCH_LBL_FIELD_HEADER_TABLE_VALUE}    no    assetname    remark    status


${ASSETMANAGEMENTINFORMATION_SEARCH_NUMCOL}    4


#-------------------------------------------- CreateEdit Check Asset Management information --------------------------------------------#

#Header Create
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_HEADER_CREATEASSET_TH}    เพิ่มอุปกรณ์
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_HEADER_CREATEASSET_EN}    Create asset
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_HEADER_CREATEASSET_LOCATOR}   id=lblAddCheckAsset

#Header Edit
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_HEADER_EDITASSETDETAIL_TH}    แก้ไขข้อมูลอุปกรณ์
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_HEADER_EDITASSETDETAIL_EN}    Edit asset detail
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_HEADER_EDITASSETDETAIL_LOCATOR}   id=lblEditCheckAsset


#ชื่ออุปกรณ์ภาษาไทย
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_ASSETNAMETH_TH}    ชื่ออุปกรณ์ภาษาไทย
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_ASSETNAMETH_EN}    Asset name (Thai)
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_ASSETNAMETH_LOCATOR}    id=lblAssetNameTh
${ASSETMANAGEMENTINFORMATION_ADDEDIT_TXT_ASSETNAMETH_LOCATOR}    id=txtAssetNameTh
${ASSETMANAGEMENTINFORMATION_ADDEDIT_ASSETNAMETH_VALUE}    อย่างสีเหลือง
${ASSETMANAGEMENTINFORMATION_ADDEDIT_ASSETNAMETH_VALUE2}    เทสดูสิ


#ชื่ออุปกรณ์ภาษาอังกฤษ
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_ASSETNAMEEN_TH}    ชื่ออุปกรณ์ภาษาอังกฤษ
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_ASSETNAMEEN_EN}    Asset name (English)
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_ASSETNAMEEN_LOCATOR}    id=lblAssetNameEn
${ASSETMANAGEMENTINFORMATION_ADDEDIT_TXT_ASSETNAMEEN_LOCATOR}    id=txtAssetNameEn
${ASSETMANAGEMENTINFORMATION_ADDEDIT_ASSETNAMEEN_VALUE}    Yellow
${ASSETMANAGEMENTINFORMATION_ADDEDIT_ASSETNAMEEN_VALUE2}    LongTest


#หมายเหตุ
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_REMARK_TH}    หมายเหตุ
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_REMARK_EN}    Remark
${ASSETMANAGEMENTINFORMATION_ADDEDIT_LBL_REMARK_LOCATOR}    id=lblRemark
${ASSETMANAGEMENTINFORMATION_ADDEDIT_TXT_ASSETNAMETHAI_LOCATOR}    id=txtRemark
${ASSETMANAGEMENTINFORMATION_ADDEDIT_REMARK_VALUE}    หมายเหตุ และ อื่นๆ
${ASSETMANAGEMENTINFORMATION_ADDEDIT_REMARK_VALUE_EN}    Remark Other 


#Cancel button
${ASSETMANAGEMENTINFORMATION_ADDEDIT_BTN_CANCEL_TH}    ยกเลิก
${ASSETMANAGEMENTINFORMATION_ADDEDIT_BTN_CANCEL_EN}    Cancel
${ASSETMANAGEMENTINFORMATION_ADDEDIT_BTN_CANCEL_LOCATOR}    id=btnCancel

#Save button
${ASSETMANAGEMENTINFORMATION_ADDEDIT_BTN_SAVE_TH}    บันทึก
${ASSETMANAGEMENTINFORMATION_ADDEDIT_BTN_SAVE_EN}    Save
${ASSETMANAGEMENTINFORMATION_ADDEDIT_BTN_SAVE_LOCATOR}    id=btnSave



################################################################-- Value --################################################################
#Status *
${ASSETMANAGEMENTINFORMATION_STATUS_TH_VALUE1}    ใช้งาน
${ASSETMANAGEMENTINFORMATION_STATUS_EN_VALUE1}    Active
${ASSETMANAGEMENTINFORMATION_STATUSID_VALUE1}    1
${ASSETMANAGEMENTINFORMATION_STATUS_TH_VALUE2}    ไม่ใช้งาน
${ASSETMANAGEMENTINFORMATION_STATUS_EN_VALUE2}    InActive
${ASSETMANAGEMENTINFORMATION_STATUSID_VALUE2}    0

#Asset name *
${ASSETMANAGEMENTINFORMATION_ASSETNAME_TH_VALUE1}    เทส
${ASSETMANAGEMENTINFORMATION_ASSETNAME_EN_VALUE1}    test


#name file 
${ASSETMANAGEMENTINFORMATION_FILENAME_VALUE}    M22_1_0_1_000_CheckAssetManagement_Error_Search_VerifyAction.sql
${ASSETMANAGEMENTINFORMATION_DELETETAT_VALUE}    '2021-10-20 15:15:38'


#capture page screenshot
${ASSETMANAGEMENTINFORMATION_SEARCH_M22_0_1_1_000_SUCCESS_SCREENSHOT}    M22_0_1_1_000_CheckAssetManagement_Success_Search_VerifyScreen.png
${ASSETMANAGEMENTINFORMATION_SEARCH_M22_1_0_1_000_SUCCESS_SCREENSHOT}    M22_1_0_1_000_CheckAssetManagement_Success_Search_VerifyAction.png
${ASSETMANAGEMENTINFORMATION_SEARCH_M22_1_0_1_000_ERROR_SCREENSHOT}    M22_1_0_1_000_CheckAssetManagement_Error_Search_VerifyAction.png

${ASSETMANAGEMENTINFORMATION_CREATE_M22_0_1_2_000_SUCCESS_SCREENSHOT}    M22_0_1_2_000_CheckAssetManagement_Success_Create_VerifyScreen.png
${ASSETMANAGEMENTINFORMATION_CREATE_M22_1_0_1_000_SUCCESS_SCREENSHOT}    M22_1_0_1_000_CheckAssetManagement_Success_Create_VerifyAction.png
${ASSETMANAGEMENTINFORMATION_CREATE_M22_1_0_1_000_ERROR_SCREENSHOT}    M22_1_0_1_000_CheckAssetManagement_Error_Create_VerifyAction.png

${ASSETMANAGEMENTINFORMATION_EDIT_M22_0_1_3_000_SUCCESS_SCREENSHOT}    M22_0_1_3_000_CheckAssetManagement_Success_Edit_VerifyScreen.png
${ASSETMANAGEMENTINFORMATION_EDIT_M22_1_1_3_000_SUCCESS_SCREENSHOT}    M22_1_1_3_000_CheckAssetManagement_Success_Edit_VerifyAction.png
${ASSETMANAGEMENTINFORMATION_EDIT_M22_1_0_1_000_ERROR_SCREENSHOT}    M22_1_0_1_000_CheckAssetManagement_Error_Edit_VerifyAction.png
