*** Keywords ***
################################################################-- Set Data for check value table View Income Detail--################################################################
Set Data for check value table View Income Detail
    #Set field header table To Array
	${numCol}=    Convert To Integer    ${ROOMMANAGEMENT_VIEW_NUMCOL}
	#Set field header table To Array
	@{fieldArrDataTable}=    Create List	
	Append To List    ${fieldArrDataTable}    @{ROOMMANAGEMENT_VIEW_LBL_FIELD_HEADER_TABLE_VALUE_TH}
	# Append To List    ${fieldArrDataTable}    no    banknameTh    bankAccountType    bankAccountName    bankAccountPromptPayNumber    status
	#Set Num field To Array
	@{arrNumfield}=    Create List	
	Append To List    ${arrNumfield}    ${numCol-2}    ${numCol-1}
	#Set Num Col To Array
	@{arrNumCol}=    Create List	
	Append To List    ${arrNumCol}    ${numCol-1}    ${numCol}
	[Return]    ${numCol}    ${fieldArrDataTable}    ${arrNumfield}    ${arrNumCol}

Set Data for check value table Income Detail
    #Set field header table To Array
	${numCol}=    Convert To Integer    ${ROOMMANAGEMENT_ADDEDITADMIN_NUMCOL}
	#Set field header table To Array
	@{fieldArrDataTable}=    Create List	
	Append To List    ${fieldArrDataTable}    @{ROOMMANAGEMENT_ADDEDITADMIN_LBL_FIELD_HEADER_TABLE_VALUE_TH}
	#Set Num field To Array
	@{arrNumfield}=    Create List	
	Append To List    ${arrNumfield}    ${numCol-2}    ${numCol-1}
	#Set Num Col To Array
	@{arrNumCol}=    Create List	
	Append To List    ${arrNumCol}    ${numCol-1}    ${numCol}
	[Return]    ${numCol}    ${fieldArrDataTable}    ${arrNumfield}    ${arrNumCol}



Check Value Table Income Details
    #================ Check Value Table ================
	#====== Verify DB ==========
    #Inquiry for verify DB  
    ${resultSearchGetIncomeDetail}=    Run keyword And Continue On Failure    Request Verify DB Check Data Search Check Room Management    ${MYSQL_TYPE_CHECKROOMMANAGEMENT_SEARCH_INCOMEDETAILADMIN}    null   null   null   ${idRoom}    null
	${dataSearchGetIncomeDetail}=    Set Variable    ${resultSearchGetIncomeDetail}[0]
	Log To Console    [dataSearchGetIncomeDetail] : ${dataSearchGetIncomeDetail}
	${rowcountGetIncomeDetail}=    Set Variable    ${resultSearchGetIncomeDetail}[1]
	Log To Console    [rowcount rowcountGetIncomeDetail] : ${rowcountGetIncomeDetail}
	
	Set Global Variable    ${rowcountIncomeDetail}    ${resultSearchGetIncomeDetail}[1]
	Log To Console    [rowcount rowcountIncomeDetail] : ${rowcountIncomeDetail}

	${checkNodata}=    Run Keyword If    '${rowcountGetIncomeDetail}'=='0'    Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_RESULT_NODATA_LOCATOR}    ${DEFAULT_LBL_NODATA_TH}    #Nodata
    ...    ELSE IF    '${rowcountGetIncomeDetail}'!='0'    Check Value Table Income Detail    ${DEFAULT_TH}     ${rowcountGetIncomeDetail}    ${dataSearchGetIncomeDetail}



Create CreateRoomAdmin input all field data

	#Click Add
	Click Element Page    ${ROOMMANAGEMENT_SEARCHADMIN_BTN_ADDROOM_LOCATOR}
	# Create room
	Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_TH}

	#Room no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ROOMNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ROOMNO_LOCATOR}

	#house no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_HOUSENO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_HOUSENO_LOCATOR}

	#Area (square meter)
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_AREA_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_VALUE_LOCATOR}

	#Water meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_WATERMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_WATERMETERNO_LOCATOR}

	#Electric meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ELECTRICMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ELECTRICMETERNO_LOCATOR}

	#Water meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_WATERMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Electric meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_ELECTRICMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Click Save
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVE_LOCATOR}


	#Income code
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMETH_VALUE}
	Sleep    0.5s

	#Click Save Income code
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}

	Sleep   11s

	#Click x
	Click Element Page    ${ROOMMANAGEMENT_BTN_CLOSE_LOCATOR}

	# ================ Verify DB ================    
    Request Verify DB Check Data Create Room    ${MYSQL_TYPE_CREATE_ALLFIELD}    ${ROOMMANAGEMENT_ACCOUNTID_VALUE}    ${ROOMMANAGEMENT_ROOMNO_VALUE}    ${ROOMMANAGEMENT_PROPERTYID_VALUE}    ${ROOMMANAGEMENT_BUILDINGID_VALUE}    ${ROOMMANAGEMENT_ORDERBY_VALUE}    

Create CreateRoomAdmin input all field data EN

	#Click Add
	Click Element Page    ${ROOMMANAGEMENT_SEARCHADMIN_BTN_ADDROOM_LOCATOR}
	# Create room
	Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_EN}

	#Room no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ROOMNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ROOMNO_LOCATOR}

	#house no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_HOUSENO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_HOUSENO_LOCATOR}

	#Area (square meter)
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_AREA_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_VALUE_LOCATOR}

	#Water meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_WATERMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_WATERMETERNO_LOCATOR}

	#Electric meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ELECTRICMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ELECTRICMETERNO_LOCATOR}

	#Water meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_WATERMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Electric meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_ELECTRICMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Click Save
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVE_LOCATOR}


	#Income code
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMEEN_VALUE}
	Sleep    0.5s

	#Click Save Income code
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}

	Sleep   11s

	#Click x
	Click Element Page    ${ROOMMANAGEMENT_BTN_CLOSE_LOCATOR}

	# ================ Verify DB ================    
    Request Verify DB Check Data Create Room    ${MYSQL_TYPE_CREATE_ALLFIELD}    ${ROOMMANAGEMENT_ACCOUNTID_VALUE}    ${ROOMMANAGEMENT_ROOMNO_VALUE}    ${ROOMMANAGEMENT_PROPERTYID_VALUE}    ${ROOMMANAGEMENT_BUILDINGID_VALUE}    ${ROOMMANAGEMENT_ORDERBY_VALUE}    


Create CreateRoomAdmin input all field data no verify db

	#Click Add
	Click Element Page    ${ROOMMANAGEMENT_SEARCHADMIN_BTN_ADDROOM_LOCATOR}
	# Create room
	Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_TH}

	#Room no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ROOMNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ROOMNO_LOCATOR}

	#house no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_HOUSENO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_HOUSENO_LOCATOR}

	#Area (square meter)
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_AREA_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_VALUE_LOCATOR}

	#Water meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_WATERMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_WATERMETERNO_LOCATOR}

	#Electric meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ELECTRICMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ELECTRICMETERNO_LOCATOR}

	#Water meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_WATERMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Electric meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_ELECTRICMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Click Save
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVE_LOCATOR}


	#Income code
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMEEN_VALUE}
	Sleep    0.5s

	#Click Save Income code
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}

	#Click x
	Click Element Page    ${ROOMMANAGEMENT_BTN_CLOSE_LOCATOR}

	



Create CreateRoomAdmin input required field data

	#Click Add
	Click Element Page    ${ROOMMANAGEMENT_SEARCHADMIN_BTN_ADDROOM_LOCATOR}
	# Create room
	Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_TH}

	#Room no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ROOMNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ROOMNO_LOCATOR}

	#Water meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_WATERMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_WATERMETERNO_LOCATOR}

	#Electric meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ELECTRICMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ELECTRICMETERNO_LOCATOR}

	#Water meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_WATERMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Electric meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_ELECTRICMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Click Save
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVE_LOCATOR}


	#Income code
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMETH_VALUE}
	Sleep    0.5s

	#Click Save Income code
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}



	#Click x
	Click Element Page    ${ROOMMANAGEMENT_BTN_CLOSE_LOCATOR}

	# ================ Verify DB ================    
    Request Verify DB Check Data Create Room    ${MYSQL_TYPE_CREATE_REQUIREDFIELD}    ${ROOMMANAGEMENT_ACCOUNTID_VALUE}    ${ROOMMANAGEMENT_ROOMNO_VALUE}    ${ROOMMANAGEMENT_PROPERTYID_VALUE}    ${ROOMMANAGEMENT_BUILDINGID_VALUE}    ${ROOMMANAGEMENT_ORDERBY_VALUE}    
    

Create CreateRoomAdmin input required field data EN

	#Click Add
	Click Element Page    ${ROOMMANAGEMENT_SEARCHADMIN_BTN_ADDROOM_LOCATOR}
	# Create room
	Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_EN}

	#Room no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ROOMNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ROOMNO_LOCATOR}

	#Water meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_WATERMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_WATERMETERNO_LOCATOR}

	#Electric meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ELECTRICMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ELECTRICMETERNO_LOCATOR}

	#Water meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_WATERMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Electric meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_ELECTRICMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Click Save
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVE_LOCATOR}


	#Income code
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMEEN_VALUE}
	Sleep    0.5s

	#Click Save Income code
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}



	#Click x
	Click Element Page    ${ROOMMANAGEMENT_BTN_CLOSE_LOCATOR}

	# ================ Verify DB ================    
    Request Verify DB Check Data Create Room    ${MYSQL_TYPE_CREATE_REQUIREDFIELD}    ${ROOMMANAGEMENT_ACCOUNTID_VALUE}    ${ROOMMANAGEMENT_ROOMNO_VALUE}    ${ROOMMANAGEMENT_PROPERTYID_VALUE}    ${ROOMMANAGEMENT_BUILDINGID_VALUE}    ${ROOMMANAGEMENT_ORDERBY_VALUE}    
    


Edit RoomAdmin input all field data no verify db

	#Click Edit
	Click Element Page    ${ROOMMANAGEMENT_SEARCHADMIN_BTN_ADDROOM_LOCATOR}
	# Edit room
	Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_EDITROOMDETAIL_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_EDITROOMDETAIL_TH}

	#Room no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ROOMNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_ROOMNO_LOCATOR}

	#house no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_HOUSENO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_HOUSENO_LOCATOR}

	#Area (square meter)
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_AREA_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_VALUE2_LOCATOR}

	#Water meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_WATERMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_WATERMETERNO_LOCATOR}

	#Electric meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ELECTRICMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_ELECTRICMETERNO_LOCATOR}

	#Water meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_WATERMETERLIMITUNIT_VALUE2}
	Sleep    0.5s

	#Electric meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_ELECTRICMETERLIMITUNIT_VALUE2}
	Sleep    0.5s

	#Click Save
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVE_LOCATOR}


	#Income code
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMETH_VALUE}
	Sleep    0.5s

	#Click Save Income code
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}

	#Click x
	Click Element Page    ${ROOMMANAGEMENT_BTN_CLOSE_LOCATOR}

Edit RoomAdmin input all field data 
	# Edit room
	Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_EDITROOMDETAIL_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_EDITROOMDETAIL_TH}

	#Room no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ROOMNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_ROOMNO_LOCATOR}

	#house no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_HOUSENO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_HOUSENO_LOCATOR}

	#Area (square meter)
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_AREA_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_VALUE2_LOCATOR}

	#Water meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_WATERMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_WATERMETERNO_LOCATOR}

	#Electric meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ELECTRICMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_ELECTRICMETERNO_LOCATOR}

	Clear Element Text    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}
	#Water meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_WATERMETERLIMITUNIT_VALUE2}
	Sleep    2s

	Clear Element Text    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}
	#Electric meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_ELECTRICMETERLIMITUNIT_VALUE2}
	Sleep    2s

	#Click Save
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVE_LOCATOR}


	# #Income code
	# Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMETH_VALUE}
	# Sleep    1s

	# #Click Save Income code
	# Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}

	#Click x
	Click Element Page    ${ROOMMANAGEMENT_BTN_CLOSE_LOCATOR}

	# ================ Verify DB ================    
    Request Verify DB Check Data Edit Room    ${MYSQL_TYPE_EDIT_ALLFIELD}    ${ROOMMANAGEMENT_ACCOUNTID_VALUE}  

Edit RoomAdmin input all field data EN 
	# Edit room
	Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_EDITROOMDETAIL_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_EDITROOMDETAIL_EN}

	#Room no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ROOMNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_ROOMNO_LOCATOR}

	#house no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_HOUSENO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_HOUSENO_LOCATOR}

	#Area (square meter)
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_AREA_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_VALUE2_LOCATOR}

	#Water meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_WATERMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_WATERMETERNO_LOCATOR}

	#Electric meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ELECTRICMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_ELECTRICMETERNO_LOCATOR}

	Clear Element Text    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}
	#Water meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_WATERMETERLIMITUNIT_VALUE2}
	Sleep    2s

	Clear Element Text    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}
	#Electric meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_ELECTRICMETERLIMITUNIT_VALUE2}
	Sleep    2s

	#Click Save
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVE_LOCATOR}


	# #Income code
	# Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMETH_VALUE}
	# Sleep    1s

	# #Click Save Income code
	# Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}

	#Click x
	Click Element Page    ${ROOMMANAGEMENT_BTN_CLOSE_LOCATOR}

	# ================ Verify DB ================    
    Request Verify DB Check Data Edit Room    ${MYSQL_TYPE_EDIT_ALLFIELD}    ${ROOMMANAGEMENT_ACCOUNTID_VALUE}



Edit RoomAdmin input Required field data 
	#Edit room
	Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_EDITROOMDETAIL_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_EDITROOMDETAIL_TH}

	#Room no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ROOMNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_ROOMNO_LOCATOR}

	#Water meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_WATERMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_WATERMETERNO_LOCATOR}

	#Electric meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ELECTRICMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_ELECTRICMETERNO_LOCATOR}

	Clear Element Text    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}
	#Water meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_WATERMETERLIMITUNIT_VALUE2}
	Sleep    2s

	Clear Element Text    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}
	#Electric meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_ELECTRICMETERLIMITUNIT_VALUE2}
	Sleep    2s

	#Click Save
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVE_LOCATOR}


	# #Income code
	# Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMETH_VALUE}
	# Sleep    1s

	# #Click Save Income code
	# Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}

	#Click x
	Click Element Page    ${ROOMMANAGEMENT_BTN_CLOSE_LOCATOR}

	# ================ Verify DB ================    
    Request Verify DB Check Data Edit Room    ${MYSQL_TYPE_EDIT_REQUIREDFIELD}    ${ROOMMANAGEMENT_ACCOUNTID_VALUE}  


Edit RoomAdmin input Required field data EN 
	#Edit room
	Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_EDITROOMDETAIL_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_EDITROOMDETAIL_EN}

	#Room no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ROOMNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_ROOMNO_LOCATOR}

	#Water meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_WATERMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_WATERMETERNO_LOCATOR}

	#Electric meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ELECTRICMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE2_ELECTRICMETERNO_LOCATOR}

	Clear Element Text    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}
	#Water meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_WATERMETERLIMITUNIT_VALUE2}
	Sleep    2s

	Clear Element Text    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}
	#Electric meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_ELECTRICMETERLIMITUNIT_VALUE2}
	Sleep    2s

	#Click Save
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVE_LOCATOR}


	# #Income code
	# Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMETH_VALUE}
	# Sleep    1s

	# #Click Save Income code
	# Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}

	#Click x
	Click Element Page    ${ROOMMANAGEMENT_BTN_CLOSE_LOCATOR}

	# ================ Verify DB ================    
    Request Verify DB Check Data Edit Room    ${MYSQL_TYPE_EDIT_REQUIREDFIELD}    ${ROOMMANAGEMENT_ACCOUNTID_VALUE}
    




CreateRoomAdmin input required field data for check income code

	#Click Add
	Click Element Page    ${ROOMMANAGEMENT_SEARCHADMIN_BTN_ADDROOM_LOCATOR}
	# Create room
	Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_TH}

	#Room no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ROOMNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ROOMNO_LOCATOR}

	#Water meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_WATERMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_WATERMETERNO_LOCATOR}

	#Electric meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ELECTRICMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ELECTRICMETERNO_LOCATOR}

	#Water meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_WATERMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Electric meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_ELECTRICMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Click Save
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVE_LOCATOR}


	# #Income code
	# Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMETH_VALUE}
	# Sleep    0.5s

	# #Click Save Income code
	# Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}

	# #Click x
	Click Element Page    ${ROOMMANAGEMENT_BTN_CLOSE_LOCATOR}

	# ================ Verify DB ================    
    Request Verify DB Check Data Create Room    ${MYSQL_TYPE_CREATE_REQUIREDFIELD}    ${ROOMMANAGEMENT_ACCOUNTID_VALUE}    ${ROOMMANAGEMENT_ROOMNO_VALUE}    ${ROOMMANAGEMENT_PROPERTYID_VALUE}    ${ROOMMANAGEMENT_BUILDINGID_VALUE}    ${ROOMMANAGEMENT_ORDERBY_VALUE}    


CreateRoomAdmin input required field data for check income code EN

	#Click Add
	Click Element Page    ${ROOMMANAGEMENT_SEARCHADMIN_BTN_ADDROOM_LOCATOR}
	# Create room
	Wait Until Contains Element Text Should Be    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_CREATEROOM_EN}

	#Room no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ROOMNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ROOMNO_LOCATOR}

	#Water meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_WATERMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_WATERMETERNO_LOCATOR}

	#Electric meter no
	Wait Until Contains Input Text    ${ROOMMANAGEMENT_ADDEDITADMIN_TXT_ELECTRICMETERNO_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_VALUE_ELECTRICMETERNO_LOCATOR}

	#Water meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_WATERMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_WATERMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Electric meter limit unit
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_ELECTRICMETERLIMITUNIT_CLASS_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_ELECTRICMETERLIMITUNIT_VALUE}
	Sleep    0.5s

	#Click Save
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVE_LOCATOR}


	# #Income code
	# Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMETH_VALUE}
	# Sleep    0.5s

	# #Click Save Income code
	# Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}

	# #Click x
	Click Element Page    ${ROOMMANAGEMENT_BTN_CLOSE_LOCATOR}

	# ================ Verify DB ================    
    Request Verify DB Check Data Create Room    ${MYSQL_TYPE_CREATE_REQUIREDFIELD}    ${ROOMMANAGEMENT_ACCOUNTID_VALUE}    ${ROOMMANAGEMENT_ROOMNO_VALUE}    ${ROOMMANAGEMENT_PROPERTYID_VALUE}    ${ROOMMANAGEMENT_BUILDINGID_VALUE}    ${ROOMMANAGEMENT_ORDERBY_VALUE}    
    


Create Income input all field data Check Table
	#Click room
	Click Element Page    ${roomNolocator}

	#Click Income detail
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_INCOMEDETAILS_LOCATOR}

	#Income code
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMETH_VALUE}
	Sleep    0.5s

	#Click Save Income code
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}
	Sleep    15s

Create Income input all field data Check Table EN
	#Click room
	Click Element Page    ${roomNolocator}

	#Click Income detail
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_INCOMEDETAILS_LOCATOR}

	#Income code
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMEEN_VALUE}
	Sleep    0.5s

	#Click Save Income code
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}
	Sleep    15s


Edit Income input all field data Check Table
	#Click room
	Click Element Page    ${roomNolocator}

	#Click Income detail
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_INCOMEDETAILS_LOCATOR}

	#Income code
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMETH_VALUE2}
	Sleep    0.5s

	#Click Save Income code
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}
	Sleep    15s

Edit Income input all field data Check Table EN
	#Click room
	Click Element Page    ${roomNolocator}

	#Click Income detail
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_LBL_INCOMEDETAILS_LOCATOR}

	#Income code
	Select Dropdown    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_LIST_LOCATOR}    ${ROOMMANAGEMENT_ADDEDITADMIN_DDL_INCOMECODE_CLASS_LOCATOR}    ${DATA_INCOMECODE_NAMEEN_VALUE2}
	Sleep    0.5s

	#Click Save Income code
	Click Element Page    ${ROOMMANAGEMENT_ADDEDITADMIN_BTN_SAVEINCOMECODE_LOCATOR}
	Sleep    15s
