*** Keywords ***
################################################################-- Create Employee management--################################################################
Create Employee management

    #Click Icon Create
	Click Element Page    ${EMPLOYEEMANAGEMENTINFORMATION_BTN_ADD_LOCATOR}
    Sleep    3s

	#Select Dropdown : Employee Type  
	Select Dropdown    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_DDL_EMPLOYEETYPE_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_VALUE_DDL_EMPLOYEETYPE_LIST_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_VALUE_DDL_EMPLOYEETYPE_CLASS_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_VALUE_DDL_CLEANINGSTAFF_TH}
	Sleep    0.5s

	# Select Dropdown : Title  
	Select Dropdown    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_DDL_TITLE_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_VALUE_DDL_TITLE_LIST_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_VALUE_DDL_TITLE_CLASS_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_VALUE_DDL_MR_TH}
	Sleep    0.5s

	# Input Firstname
	Wait Until Contains Input Text    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_TXT_FIRSTNAME_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_FIRSTNAME_VALUE}

	# Input Lastname
	Wait Until Contains Input Text    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_TXT_LASTNAME_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_LASTNAME_VALUE}

	# Input Phone Number
	Wait Until Contains Input Text    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_TXT_PHONENUMBER_LOCATOR}    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_PHONENUMBER_VALUE}

	#Click Save
	Click Element Page    ${EMPLOYEEMANAGEMENTINFORMATION_CREATE_BTN_SAVE_LOCATOR}
################################################################################################################################
